#!/usr/bin/env bash

# take session name from the file
session=$(basename ${0%.*})

tmux rename-window -t $session:1 dev

tmux new-window -t $session -n debug

tmux send-keys -t $session:1 'task dev' C-m

tmux select-window -t $session:1
