#!/usr/bin/env sh

BRANCH=$(git rev-parse --abbrev-ref HEAD)

if [ "$BRANCH" = "master" ] || [ "$BRANCH" = "main" ]; then
    echo "ERROR: You are trying to commit directly to the $BRANCH branch, which is not allowed."
    echo "Please create a feature branch and use pull requests instead."
    exit 1
fi

if git grep --cached -l -E -e "f(it|describe|context) ['\"]" -e "Pry::ColorPrinter\.pp\(\w*)"; then
    echo -e "\n"
    echo 'Commit contains focused tests or puts statements.'
    exit 1
fi

if files=$(git grep --cached -l -E -e "binding.irb"); then
    echo -e "\n"
    echo "Commit contains debugger statements in:"
    echo "$files"
    exit 1
fi

# Run Rubocop on staged .rb files
rb_files=$(git diff --cached --name-only --diff-filter=ACM | grep ".rb$")

cmd="docker-compose exec test rubocop"

if [[ $rb_files ]]; then
    if ! $cmd $rb_files; then
        echo "Rubocop failed on staged file. Please fix the errors and try again."
        exit 1
    fi
fi

ts_files=$(git diff --cached --name-only --diff-filter=ACM | grep ".ts$")
prettier_cmd="prettier -l"

if [[ $ts_files ]]; then
    if ! $prettier_cmd $ts_files; then
        echo "Prettier failed on a staged file. Please fix the errors and try again."
        exit 1
    fi
fi

erb_files=$(git diff --cached --name-only --diff-filter=ACM | grep ".erb$")
erb_cmd="docker exec spabreaks bundle exec erb_lint --lint-all"

if [[ $erb_files ]]; then
    if ! $erb_cmd; then
        echo "Erb failed on a staged file. Please fix the errors and try again."
        exit 1
    fi
fi
