version: '3'

tasks:
  gpg-import-keys:
    cmds:
      - gpg --import ~/nix-config/users/pl/pgp.asc

  sops-edit-keys:
    cmds:
      - sops secrets/secrets.yaml

  sops-stub-keys:
    vars:
      SOPS_AGE_DIR: ~/.config/sops/age
    cmds:
      - mkdir -p {{.SOPS_AGE_DIR}}
      - test -f {{.SOPS_AGE_DIR}}/keys.txt || echo "AGE-SECRET-KEY-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" > {{.SOPS_AGE_DIR}}/keys.txt

  docs-fetch:
    desc: Fetch markdown documentation from Github URLs
    cmds:
      - fetch_gh_docs
    silent: true
