#!/bin/sh

# Automatically adds branch name and branch description to every commit message.
#
NAME=$(git branch | grep '*' | sed 's/* //') 
DESCRIPTION=$(git config branch."$NAME".description)

echo "[$NAME]"': '$(cat "$1") > "$1"
if [ -n "$DESCRIPTION" ] 
then
   echo "" >> "$1"
   echo $DESCRIPTION >> "$1"
fi 

if [[ -f .git/hooks/commit-msg ]]; then
    if ! .git/hooks/commit-msg "$@"; then
        echo "Local pre-commit hook has failed"
        exit 1
    fi
fi
