#!/usr/bin/env bash

# Only run if we're checking out a branch (not individual files)
if [ "$3" = "1" ]; then
    source $HOME/nix-config/home/config/zsh/aliases.d/gh/set_pr_info.zsh

    save_pr_info
fi
