#!/usr/bin/env bash

if [[ "$PWD" != "$HOME/code"* ]]; then
    exit 0
fi

if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    exit 0
fi

session=$(tmux display-message -p '#S')

tmux rename-window -t $session:1 edit

tmux new-window -t $session -n gitui
tmux new-window -t $session -n run
tmux new-window -t $session -n test

tmux send-keys -t $session:1 'nvim' C-m
tmux send-keys -t $session:2 'gitui' C-m

tmux select-window -t $session:2
